version: '3'
services:
    router:
      image: avail/valhalla:3.0.8
      container_name: valhalla_latest
      ports:
        - "8005:8002"
      volumes:
        - ./data:/data
        - ./scripts:/scripts
      command: /scripts/run
